name: skinguard_ai
description: Offline AI skin lesion screening
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  onnxruntime: ^1.4.1
  image: ^4.2.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0

  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^10.1.2

  crypto: ^3.0.5
  shared_preferences: ^2.3.3

  google_fonts: ^6.2.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#0C1512"
  android_12:
    color: "#0C1512"
  android: true
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_1024.png"

  adaptive_icon_background: "assets/icon/adaptive_bg.png"
  adaptive_icon_foreground: "assets/icon/adaptive_fg.png"
  adaptive_icon_monochrome: "assets/icon/adaptive_fg.png"

  remove_alpha_ios: true
  min_sdk_android: 23

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/icon/
